workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - "your-email@example.com"  # ضع بريدك الإلكتروني هنا لتصلك إشعارات البناء
